export const livematches = {
  success: true,
  data: {
    match: [
      {
        h2h: "https://livescore-api.com/api-client/teams/head2head.json?key=xoFjaCB86VrE2Shg&secret=EbFAzESgLafuQEyn2eHdQjlXeNBhFTyk&team1_id=7463&team2_id=204",
        added: "2023-10-30 07:45:01",
        league_name: "",
        last_changed: "2023-10-30 09:56:22",
        country: {
          name: "Indonesia",
          id: 90,
          flag: "IDN.png",
        },
        has_lineups: true,
        ht_score: "0 - 0",
        away_id: 204,
        time: "FT",
        score: "1 - 1",
        location: "Stadion Krakatau Steel",
        league_id: 0,
        et_score: "",
        id: 471135,
        competition_name: "GO-JEK Liga 1",
        competition_id: 27,
        scheduled: "08:11",
        fixture_id: 1624757,
        events:
          "https://livescore-api.com/api-client/scores/events.json?key=xoFjaCB86VrE2Shg&secret=EbFAzESgLafuQEyn2eHdQjlXeNBhFTyk&id=471135",
        status: "FINISHED",
        home_name: "RANS Nusantara",
        odds: {
          pre: {
            "1": 2.18,
            "2": 3.1,
            X: 2.9,
          },
          live: {
            "1": 19,
            "2": 19,
            X: 1.02,
          },
        },
        home_id: 7463,
        ft_score: "1 - 1",
        ps_score: "",
        away_name: "PSM Makassar",
        federation: null,
        outcomes: {
          half_time: "X",
          full_time: "X",
          extra_time: null,
        },
      },
      {
        h2h: "https://livescore-api.com/api-client/teams/head2head.json?key=xoFjaCB86VrE2Shg&secret=EbFAzESgLafuQEyn2eHdQjlXeNBhFTyk&team1_id=6950&team2_id=5457",
        added: "2023-10-30 10:46:04",
        league_name: "",
        last_changed: "2023-10-30 11:34:06",
        country: {
          name: "Armenia",
          id: 190,
          flag: "ARM.png",
        },
        has_lineups: true,
        ht_score: "",
        away_id: 5457,
        time: "32",
        score: "0 - 0",
        location: "-",
        league_id: 0,
        et_score: "",
        id: 471138,
        competition_name: "1st League",
        competition_id: 239,
        scheduled: "11:00",
        fixture_id: 1635602,
        events:
          "https://livescore-api.com/api-client/scores/events.json?key=xoFjaCB86VrE2Shg&secret=EbFAzESgLafuQEyn2eHdQjlXeNBhFTyk&id=471138",
        status: "IN PLAY",
        home_name: "BKMA II",
        odds: {
          pre: {
            "1": null,
            "2": null,
            X: null,
          },
          live: {
            "1": null,
            "2": null,
            X: null,
          },
        },
        home_id: 6950,
        ft_score: "",
        ps_score: "",
        away_name: "Ararat II",
        federation: null,
        outcomes: {
          half_time: null,
          full_time: null,
          extra_time: null,
        },
      },
      {
        h2h: "https://livescore-api.com/api-client/teams/head2head.json?key=xoFjaCB86VrE2Shg&secret=EbFAzESgLafuQEyn2eHdQjlXeNBhFTyk&team1_id=7515&team2_id=5453",
        added: "2023-10-30 10:46:04",
        league_name: "",
        last_changed: "2023-10-30 11:34:06",
        country: {
          name: "Armenia",
          id: 190,
          flag: "ARM.png",
        },
        has_lineups: true,
        ht_score: "",
        away_id: 5453,
        time: "32",
        score: "0 - 0",
        location: "Mika Stadium",
        league_id: 0,
        et_score: "",
        id: 471139,
        competition_name: "1st League",
        competition_id: 239,
        scheduled: "11:00",
        fixture_id: 1635603,
        events:
          "https://livescore-api.com/api-client/scores/events.json?key=xoFjaCB86VrE2Shg&secret=EbFAzESgLafuQEyn2eHdQjlXeNBhFTyk&id=471139",
        status: "IN PLAY",
        home_name: "Mika Yerevan",
        odds: {
          pre: {
            "1": null,
            "2": null,
            X: null,
          },
          live: {
            "1": null,
            "2": null,
            X: null,
          },
        },
        home_id: 7515,
        ft_score: "",
        ps_score: "",
        away_name: "Ararat-Armenia II",
        federation: null,
        outcomes: {
          half_time: null,
          full_time: null,
          extra_time: null,
        },
      },
      {
        h2h: "https://livescore-api.com/api-client/teams/head2head.json?key=xoFjaCB86VrE2Shg&secret=EbFAzESgLafuQEyn2eHdQjlXeNBhFTyk&team1_id=7769&team2_id=5014",
        added: "2023-10-30 10:46:05",
        league_name: "",
        last_changed: "2023-10-30 11:34:06",
        country: {
          name: "Armenia",
          id: 190,
          flag: "ARM.png",
        },
        has_lineups: true,
        ht_score: "",
        away_id: 5014,
        time: "32",
        score: "0 - 0",
        location: "--",
        league_id: 0,
        et_score: "",
        id: 471140,
        competition_name: "1st League",
        competition_id: 239,
        scheduled: "11:00",
        fixture_id: 1642307,
        events:
          "https://livescore-api.com/api-client/scores/events.json?key=xoFjaCB86VrE2Shg&secret=EbFAzESgLafuQEyn2eHdQjlXeNBhFTyk&id=471140",
        status: "IN PLAY",
        home_name: "Nikarm",
        odds: {
          pre: {
            "1": null,
            "2": null,
            X: null,
          },
          live: {
            "1": null,
            "2": null,
            X: null,
          },
        },
        home_id: 7769,
        ft_score: "",
        ps_score: "",
        away_name: "Syunik",
        federation: null,
        outcomes: {
          half_time: null,
          full_time: null,
          extra_time: null,
        },
      },
      {
        h2h: "https://livescore-api.com/api-client/teams/head2head.json?key=xoFjaCB86VrE2Shg&secret=EbFAzESgLafuQEyn2eHdQjlXeNBhFTyk&team1_id=6020&team2_id=2007",
        added: "2023-10-30 10:46:06",
        league_name: "",
        last_changed: "2023-10-30 11:34:06",
        country: {
          name: "Russia",
          id: 12,
          flag: "RUS.png",
        },
        has_lineups: true,
        ht_score: "",
        away_id: 2007,
        time: "34",
        score: "0 - 1",
        location: "Khimik Stadium",
        league_id: 0,
        et_score: "",
        id: 471141,
        competition_name: "National Football League 2",
        competition_id: 310,
        scheduled: "11:00",
        fixture_id: 0,
        events:
          "https://livescore-api.com/api-client/scores/events.json?key=xoFjaCB86VrE2Shg&secret=EbFAzESgLafuQEyn2eHdQjlXeNBhFTyk&id=471141",
        status: "IN PLAY",
        home_name: "Tver FC",
        odds: {
          pre: {
            "1": null,
            "2": null,
            X: null,
          },
          live: {
            "1": null,
            "2": null,
            X: null,
          },
        },
        home_id: 6020,
        ft_score: "",
        ps_score: "",
        away_name: "FC Luki-Energiya Velikiye Luki",
        federation: null,
        outcomes: {
          half_time: null,
          full_time: null,
          extra_time: null,
        },
      },
      {
        h2h: "https://livescore-api.com/api-client/teams/head2head.json?key=xoFjaCB86VrE2Shg&secret=EbFAzESgLafuQEyn2eHdQjlXeNBhFTyk&team1_id=5008&team2_id=3606",
        added: "2023-10-30 11:31:05",
        league_name: "",
        last_changed: "2023-10-30 11:34:06",
        country: {
          name: "Iraq",
          id: 128,
          flag: "IRQ.png",
        },
        has_lineups: true,
        ht_score: "",
        away_id: 3606,
        time: "4",
        score: "0 - 0",
        location: "Al Kefal Olympic Stadium",
        league_id: 0,
        et_score: "",
        id: 471142,
        competition_name: "Premier League",
        competition_id: 281,
        scheduled: "11:30",
        fixture_id: 1659381,
        events:
          "https://livescore-api.com/api-client/scores/events.json?key=xoFjaCB86VrE2Shg&secret=EbFAzESgLafuQEyn2eHdQjlXeNBhFTyk&id=471142",
        status: "IN PLAY",
        home_name: "Al-qasim Sc",
        odds: {
          pre: {
            "1": null,
            "2": null,
            X: null,
          },
          live: {
            "1": null,
            "2": null,
            X: null,
          },
        },
        home_id: 5008,
        ft_score: "",
        ps_score: "",
        away_name: "Erbil",
        federation: null,
        outcomes: {
          half_time: null,
          full_time: null,
          extra_time: null,
        },
      },
    ],
  },
};
